# D:/vue/docker/docker-compose.yml (最终持久化版)

version: '3.8'

services:
  emby-toolkit:
    build: .
    container_name: emby-toolkit
    restart: unless-stopped
    volumes:
      - ./local_data:/config 
    environment:
      - APP_DATA_DIR=/config
      - PUID=1000
      - PGID=1000
    ports:
      - "5257:5257"
    networks:
      - emby-net

  nginx:
    image: nginx:1.25-alpine
    container_name: emby-proxy-nginx
    restart: unless-stopped
    ports:
      - "8097:8097"
    volumes:
      - ./local_data/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      emby-toolkit:
        condition: service_healthy
    networks:
      - emby-net

networks:
  emby-net:
    driver: bridge